### ISSUE TITLE
i will edit source code filezilla and compile 

### ISSUE THREAD

**Issue by TarrahArshad** [basvodde/filezilla#3]
i will edit source code filezilla and compile .
i install msys2 and dependencies all but when i run commande " make " i got error 

make: *** No targets specified and no makefile found.  Stop.

my question is how to i can make new .exe file from source code compile on msys2 ?
and how to i can find location code for login client event ?
and how to i can resolve this problem for make ?

thanks all my skype is tarraharshad if u can help me plz send me message. thanks

**Comment by basvodde** [comment]
This is not the real copy of Filezilla, which is hosted on sourceforge and not on github. So, I'd check that out.

Anyways, it uses automake, so you first have to generate the Makefile before you can make.

**Comment by TarrahArshad** [comment]
i no used your here source code , i used from main offical website https://wiki.filezilla-project.org/Compiling_FileZilla_3_under_Windows i flowed all step but in "Building FileZilla" title in make command i got this error

**Comment by basvodde** [comment]
Yes, you should use the official code. This one is very old.

**Comment by TarrahArshad** [comment]
can u help me bro for comppile it ?

**Comment by basvodde** [comment]
If you want to compile it, you need to learn how automake works. If you want to follow the instructions, you need to find the latest source and not this copy. This one is over 5 years old.

**Comment by TarrahArshad** [comment]
https://svn.filezilla-project.org/svn/FileZilla3/trunk   its not latest code ?

**Comment by basvodde** [comment]
Sure. But then why post the question here? This is a 5 year old copy and I do not know how to compile the current version....
