### ISSUE TITLE
Submit to the Windows Store

### ISSUE THREAD

**Issue by imsai0** [basvodde/filezilla#4]
Refer [Filezilla Appx Package](https://github.com/UWP-Open-Source-Community/FileZilla ) here.

Here is [Desktop to Appx Guide](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter) to convert Win32/.NET apps to AppX Package.

I know Filezilla is simple without having install/uninstall problems that occur in some big applications but It is easy to let the store handle the update process than all by yourself. You can also upload the AppX Package to a http server (like you always do), no need to submit to the store if you prefer that way.

WinRT is maturing fast, in a few years it could very well replace Win32 . It is easier to install directly from the store and benefit from all its features like Crash Reporting , Feedback Hub , Analytics ,
Differential Downloads , etc...

Please consider the idea!
Thanks

**Comment by basvodde** [comment]
This is not the real Filezilla. Go to ask the real repository.

**Comment by imsai0** [comment]
couldn't you submit your version of filezilla? that would be awesome

**Comment by basvodde** [comment]
No. This is not my version but a version used for exercise about bad code. Please go bother the real Filezilla people.
