### ISSUE TITLE
do not treat .. correctly

### ISSUE THREAD

**Issue by beenotung** [basvodde/filezilla#5]
I tried to upload some files and folders. Those do not excess 10 MB, but it add a lot of files into the queue over 3 GB.
Then it used up the RAM and start to use swap, (using 8GB of memory in total).

I tried redo the process with some files and folder, same bug.
I tried to update the files manually (do not select folders) then it's fine.

It seems to recursively include all 'subfolders' including `..` ...

## Versions
| Name | Version |
|----|----|
| FileZilla | 3.29.0 |
| OS | Archlinux |
| Kernel | 4.14.8-1-ARCH |

**Comment by basvodde** [comment]
This is not the main Filezilla codebase but a copy. You'll need to report bugs elsewhere.
