### ISSUE TITLE
Why is the latest version determined by many anti-virus engines as positive?

### ISSUE THREAD

**Issue by petrovnn** [basvodde/filezilla#7]
https://www.virustotal.com/#/file/3129fd5421c1a71c0673f4cae5349b4a98d4e93da9c41ace1bcacdc9ebf9c0ff/detection

![image](https://user-images.githubusercontent.com/1567284/42547798-98fdc66c-84cc-11e8-849f-33ead4e9fa0f.png)

**Comment by basvodde** [comment]
This is not the Filezilla repository but a copy for exercises. Please comment on the real Filezilla repository.
