### ISSUE TITLE
Not able to run configure script

### ISSUE THREAD

**Issue by sykyck** [basvodde/filezilla#8]
After running autogen.sh script i ran the configure script and it showed me the error 
checking for wxWidgets version >= 2.8.12 (--unicode=yes --universal=no)... yes (version 3.0.4)
checking for wxWidgets static library... no
configure: error: You need to use wxWidgets 2.8.x to compile this program.
if i have version 3.0.4 then why it is telling me to use 2.8.x 
I have kali linux rolling as my os and  i have wx-3.0/wx in my /usr/include

**Comment by basvodde** [comment]
Thanks. This Filezilla is a clone of the real project though and not making changes in it.
